import fs from "node:fs/promises";
import { createWriteStream } from "node:fs";
import path from "node:path";
import type { VenueDossier } from "../types.js";
import { ensureDir, writeText } from "../utils/fs.js";

export class DossierService {
  async writeVenueDossier(dossier: VenueDossier): Promise<string> {
    const outDir = path.resolve(process.cwd(), "out", dossier.venue.slug);
    await ensureDir(outDir);
    const filePath = path.join(outDir, "dossier.md");
    const body = [
      `# Venue Dossier: ${dossier.venue.name}`,
      "",
      `- Status: ${dossier.venue.status}`,
      `- Canonical URL: ${dossier.venue.canonicalUrl ?? "Unknown"}`,
      `- City: ${dossier.venue.city ?? "Unknown"}`,
      "",
      "## Latest Audit",
      dossier.latestAudit
        ? `- Score: ${dossier.latestAudit.score}
- Top leaks: ${dossier.latestAudit.topLeaks.map((leak) => leak.title).join(", ")}`
        : "- No audit run recorded yet.",
      "",
      "## Contacts",
      ...(dossier.contacts.length > 0
        ? dossier.contacts.map((contact) => `- ${contact.kind}: ${contact.value} (${contact.roleHint ?? "unknown"}, confidence ${contact.confidence.toFixed(2)})`)
        : ["- No contacts found."]),
      "",
      "## Outreach Threads",
      ...(dossier.threads.length > 0
        ? dossier.threads.map((thread) => `- ${thread.status}: ${thread.subject ?? "No subject"} (${thread.id})`)
        : ["- No outreach threads yet."]),
      "",
      "## Offers and Billing",
      ...(dossier.offers.length > 0
        ? dossier.offers.map((offer) => `- ${offer.pricingModel}: ${offer.status}`)
        : ["- No offers yet."]),
      ...(dossier.checkouts.length > 0
        ? dossier.checkouts.map((checkout) => `- Checkout ${checkout.id}: ${checkout.status} ${checkout.checkoutUrl ?? ""}`.trim())
        : []),
      "",
      "## Deliveries",
      ...(dossier.deliveries.length > 0
        ? dossier.deliveries.map((delivery) => `- ${delivery.status}: ${delivery.deliveryUrl ?? delivery.zipPath ?? delivery.id}`)
        : ["- No deliveries yet."]),
      "",
      "## Stage Timeline",
      ...(dossier.stageEvents.length > 0
        ? dossier.stageEvents.map((event) => `- ${event.createdAt} | ${event.stage} | ${event.eventType}${event.decision ? ` | ${event.decision}` : ""}`)
        : ["- No stage events recorded."])
    ].join("\n");
    await writeText(filePath, body);
    return filePath;
  }

  async writeClientReadme(outDir: string, venueName: string): Promise<string> {
    const filePath = path.join(outDir, "README_CLIENT.md");
    await writeText(filePath, [
      `# ${venueName} Delivery Pack`,
      "",
      "This pack includes the latest audit, fix assets, outreach drafts, and dossier export generated by Autonomous Fixer.",
      "",
      "## Files",
      "- `audit.json`: structured audit and analysis data",
      "- `report.md`: plain-language venue audit report",
      "- `dossier.md`: full timeline of decisions and stage events",
      "- `fix/`: generated booking, intake, schema, SEO, and fill-the-night assets",
      "",
      "Approve and we deploy in 24 hours."
    ].join("\n"));
    return filePath;
  }

  async writeZip(zipPath: string, sourceDir: string): Promise<void> {
    const archiver = (await import("archiver")).default;
    await ensureDir(path.dirname(zipPath));
    await new Promise<void>((resolve, reject) => {
      const output = createWriteStream(zipPath);
      const archive = archiver("zip", { zlib: { level: 9 } });
      output.on("close", () => resolve());
      archive.on("error", (error: Error) => reject(error));
      archive.pipe(output);
      archive.directory(sourceDir, false);
      void archive.finalize();
    });
  }

  async readTextIfExists(filePath: string): Promise<string | undefined> {
    try {
      return await fs.readFile(filePath, "utf8");
    } catch {
      return undefined;
    }
  }
}
